os: linux
dist: focal
language: bash
services:
  - docker
before_install:
  - docker pull debian:bullseye
  - docker run --rm -it debian:bullseye /bin/bash -c "cd /root/esa/opengeode ; ./run_tests.sh"
script:
  - echo "Is this running..."
